################################################
---
- name: "configure os at_{{ ansible_play_hosts | to_yaml }}"
  hosts: _{{ group_name | default('all') }}"
  collections:
    - linux.bootstrap
  gather_facts: no
  any_errors_fatal: true
  become: yes
  vars:
    pl_name: "configure_os"

################################################
  pre_tasks:
  - block:
    - name: "role check availibility"
      ansible.builtin.include_role:
        name: r_check_availability

    - name: "role check node os 4 rhel"
      ansible.builtin.include_role:
        name: r_check_os

    - name: "role create local facts"
      ansible.builtin.include_role:
        name: r_create_local_facts

    rescue:
    - fail:
        msg: "pre tasks_{{ pl_name }} failed"

    tags:
    - always


################################################
  tasks:
  - block:
    - name: "role create admin user"
      ansible.builtin.include_role:
        name: r_create_admin_user
      tags: 
      - create_admin_user

    - name: "role configure dns"
      ansible.builtin.include_role:
        name: r_configure_dns
      tags:
      - configure_dns

    - name: "role configure ntp service"
      ansible.builtin.include_role:
        name: r_configure_ntp
      tags: 
      - configure_ntp

    - name: "role deploy ca"
      ansible.builtin.include_role:
        name: r_deploy_ca
      tags:
      - deploy_ca

    - name: "role configure repos"
      ansible.builtin.include_role:
        name: r_configure_linux_repos_{{ runtime_dist_flag }}
      tags: 
      - configure_linux_repos

    - name: "role configure auto update"
      ansible.builtin.include_role:
        name: r_configure_auto_update_{{ runtime_dist_flag }}
      tags: 
      - configure_auto_update

    - name: "role update all"
      ansible.builtin.include_role:
        name: r_update_all_{{ runtime_dist_flag }}
      tags: 
      - update_all

    - name: "role reboot nodes"
      ansible.builtin.include_role:
        name: r_reboot_nodes
      tags: 
      - reboot_nodes

    - name: "role probe state systemd services"
      ansible.builtin.include_role:
        name: r_probe_services
      tags: 
      - probe_services

    - name: "role configure sshd service"
      ansible.builtin.include_role:
        name: r_configure_sshd
      tags: 
      - configure_sshd

    rescue:
    - ansible.builtin.fail:
        msg: "tasks_{{ pl_name }} failed"

################################################
  post_tasks:
  - block:
    - name: "role write local state facts"
      ansible.builtin.include_role:
        name: r_write_local_state_facts
      tags:
      - always

    rescue:
    - ansible.builtin.fail:
        msg: "post tasks_{{ pl_name }} failed"
