---
# tasks file for r_configure_sshd
  - block:
    - name: "disable root login on tty"
      lineinfile:
        dest: "{{ sshd_config_file }}"
        regex: "^#?PermitRootLogin"
        line: "PermitRootLogin no"
      notify: restart_sshd

    - name: "disable dns lookups"
      lineinfile:
        dest: "{{ sshd_config_file }}"
        regex: "^#?UseDNS"
        line: "UseDNS no"
      notify: restart_sshd

    rescue:
    - fail:
        msg: "error: configure sshd service"

    tags:
    - configure_sshd
